name: Deploy uat

on:
  push:
    branches:
      - uat

jobs:
  deploy:
    name: Deploy to main
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the code from the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Set up SSH agent to connect to the server
    - name: Set up SSH Agent
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    # Step 3: Deploy to the server
    - name: Deploy to Server
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
          set -e

          echo "Pulling latest code from GitHub..."
          cd ~/Fast-API
          git pull uat

          echo "Building and restarting Docker container for uat..."
          docker-compose down
          docker-compose up -d --build api-uat

          echo "Deployment to prod completed successfully!"
        EOF
