name: Deploy uat

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to main
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the code from the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Set up SSH agent to connect to the server
    - name: Set up SSH Agent
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    # Step 3: Deploy to the server
    - name: Deploy to Server
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
          set -e

          echo "Pulling latest code from GitHub..."
          cd ~/Fastapi
          git pull origin main



          if [ $? -ne 0 ]; then
            echo "Error: Failed to pull the latest code. Exiting..."
            exit 1
          fi

          echo "Building and restarting Docker container for main..."

          # Stop and remove the existing container
          docker stop mainapp || true
          docker rm mainapp || true

          # Build a new Docker image
          docker build -t main-app .

          if [ $? -ne 0 ]; then
            echo "Error: Docker build failed. Exiting..."
            exit 1
          fi

          # Run the new container
          docker run -d --name main-container -p 8000:8000 main-app

          if [ $? -eq 0 ]; then
            echo "Docker container for main is up and running!"
          else
            echo "Error: Failed to start the Docker container. Exiting..."
            exit 1
          fiOF
